config/routes.rb
Rails.application.routes.draw do

  get 'users/new'

  get 'static/home'

  get 'bookstores/new'

  post 'bookstores/create'

  get 'books/index'

  get 'books/new'

  get 'books/show'

  post 'books/store'

  get 'bookstores/coord' => 'bookstores#find_coordinates', as: :coordinates
  get 'bookstores/map' => 'bookstores#map', as: :map

  get 'users/index'

  get 'users/show'

  post '/submit_map'  => 'bookstores#map'
  get 'signup' => 'users#new'
  get   'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  get 'logout'  => 'sessions#destroy'
  
  post '/share' => 'books#share'
  post '/dislike' => 'books#dislike'
  post '/remove' => 'books#remove'

  # root 'welcome#index'

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
    resources :users
    resources :books
    resources :bookstores

  root 'static#home'

  
end

app/models/user.rb
class User < ActiveRecord::Base

	has_many :favorite_books, -> { distinct }, through: :favorites, source: :book
	has_many :favorites,  -> { order(position: :asc) }

	has_many :hated_books, -> { distinct }, through: :unfinisheds, source: :book
	has_many :unfinisheds


	has_and_belongs_to_many :genres, :join_table => :genres_users

	# validates_uniqueness_of :favorite
	# validates_uniqueness_of :unfinished

	before_save { self.email = email.downcase }
	validates(:first_name, presence: true)
	validates(:last_name, presence: true)

	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates(:email, presence: true, uniqueness: { case_sensitive: false })
	validates(:email, length: { maximum: 100 },
                    format: { with: VALID_EMAIL_REGEX })

	has_secure_password
	validates :password, presence: true, length: { minimum: 6 }, allow_nil: true
	

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:edit, :update, :index]
  before_action :correct_user,   only: [:edit, :update]
  include SessionsHelper
  include UsersHelper

  def new
  	@user = User.new
  end

  def create
    @user = User.new(user_params)
    if current_user
      flash[:danger] = "Dude, wake up. You already have an account."
      redirect_to user_path(current_user)
    elsif @user.save
      log_in @user
    	flash[:success] = "Guess what, booklover? You have an account! A bonafide account!"
      redirect_to @user
    else
      render 'new'
    end 
  end

  def show
  	@user = User.find(params[:id])
  end

  def edit
    @user=User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "There you go! Your info has been updated."
      redirect_to @user
    else
      render 'edit'
    end
  end

  def index
    @users = User.paginate(page: params[:page], :per_page => 5)
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "Your account has been terminated."
    redirect_to root_path
  end

  private

  	def user_params
      params.require(:user).permit(:username, :state, :city, :first_name, :last_name, :email, :password, :password_confirmation, :fav_author, genre_ids:[])
    end

    def logged_in_user
      unless logged_in?
        flash[:danger] = "Please log in."
        redirect_to login_path
      end
    end

    # Confirms the correct user.
    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user)
    end

end

app/helpers/users_helper.rb
module UsersHelper

	def us_states
    [
      ['Alabama', 'AL'],
      ['Alaska', 'AK'],
      ['Arizona', 'AZ'],
      ['Arkansas', 'AR'],
      ['California', 'CA'],
      ['Colorado', 'CO'],
      ['Connecticut', 'CT'],
      ['Delaware', 'DE'],
      ['District of Columbia', 'DC'],
      ['Florida', 'FL'],
      ['Georgia', 'GA'],
      ['Hawaii', 'HI'],
      ['Idaho', 'ID'],
      ['Illinois', 'IL'],
      ['Indiana', 'IN'],
      ['Iowa', 'IA'],
      ['Kansas', 'KS'],
      ['Kentucky', 'KY'],
      ['Louisiana', 'LA'],
      ['Maine', 'ME'],
      ['Maryland', 'MD'],
      ['Massachusetts', 'MA'],
      ['Michigan', 'MI'],
      ['Minnesota', 'MN'],
      ['Mississippi', 'MS'],
      ['Missouri', 'MO'],
      ['Montana', 'MT'],
      ['Nebraska', 'NE'],
      ['Nevada', 'NV'],
      ['New Hampshire', 'NH'],
      ['New Jersey', 'NJ'],
      ['New Mexico', 'NM'],
      ['New York', 'NY'],
      ['North Carolina', 'NC'],
      ['North Dakota', 'ND'],
      ['Ohio', 'OH'],
      ['Oklahoma', 'OK'],
      ['Oregon', 'OR'],
      ['Pennsylvania', 'PA'],
      ['Puerto Rico', 'PR'],
      ['Rhode Island', 'RI'],
      ['South Carolina', 'SC'],
      ['South Dakota', 'SD'],
      ['Tennessee', 'TN'],
      ['Texas', 'TX'],
      ['Utah', 'UT'],
      ['Vermont', 'VT'],
      ['Virginia', 'VA'],
      ['Washington', 'WA'],
      ['West Virginia', 'WV'],
      ['Wisconsin', 'WI'],
      ['Wyoming', 'WY']
    ]
end
	
end

app/views/users/edit.html.erb
<%= render 'layouts/header' %>

<div class="row">
<div class="col-md-8 col-md-offset-2">
    <div class="row" id="sign_in">
    <div class="col-lg-offset-2 col-lg-8" id="signin1">
      <h2>Update your Account Information</h2>
        <% if current_user?(@user) %>
        <p>If you truly must... </p> 
        <%= link_to image_tag("delete.png", class: "vel-button", 
            :onmouseover => "this.src='/assets/delete_hover1.png'", 
            :onmouseout => "this.src='/assets/delete.png'"), @user, method: :delete, data: { confirm: "You sure?" } %>
        <% end %>
    </div>
    </div>
        <div class="row">
        <div class="col-lg-12" id="signin2">
          
          <%= form_for(@user) do |f| %>
            <div class="row">
            <div class="col-lg-12">
                <%= render 'shared/error_messages' %>
            </div>
            </div>

            <div class="row">
            <div class="col-lg-6" id="essentials">
                <h3>The Essentials</h3>
                <%= f.label :username %>
                <%= f.text_field :username, class: 'form-control' %>

                <%= f.label :first_name %>
                <%= f.text_field :first_name, class: 'form-control' %>

                <%= f.label :last_name %>
                <%= f.text_field :last_name, class: 'form-control' %>

                <%= f.label :city %>
                <%= f.text_field :city, class: 'form-control' %>

                <%= f.label :state %><br>
                <%= f.select :state, us_states %><br>

                <%= f.label :email %>
                <%= f.email_field :email, class: 'form-control' %>

                <%= f.label :password %>
                <%= f.password_field :password, class: 'form-control' %>

                <%= f.label :password_confirmation, "Confirmation" %>
                <%= f.password_field :password_confirmation, class: 'form-control' %>
            </div>
            <div class="col-lg-6 fun_stuff">
                <h3>The Fun Stuff</h3>
                <%= f.label :fav_author, "Favorite Author" %>
                <%= f.text_field :fav_author, class: 'form-control' %><br>
                <div class="field">
                 
                  <fieldset class="col-lg-offset-1 col-lg-11" id="group">
                    <legend>Pick your favorite Genres</legend>
                  <%= f.collection_check_boxes :genre_ids, Genre.all, :id, :name do |b| %>
                    <div class="collection-check-box">
                      <%= b.check_box %>
                      <%= b.label %>
                    </div>
                  <% end %>
                  </fieldset>
                </div>
            </div>
            </div>
            <div class="row">
            <div class="col-lg-offset-4 col-lg-4">
                <div id="signin_button">
                  <%= image_submit_tag("paw.png", class: "vel-button",
                    :onmouseover => "this.src='/assets/paw_hover.png'", 
                    :onmouseout => "this.src='/assets/paw.png'")  %>
                </div>
            </div>
            </div>
          <% end %>
          
        </div>
    </div>
  </div>

</div>
</div>

app/views/users/index.html.erb
<%= render 'layouts/header' %>

<div class="row">
	<div class="col-lg-offset-3 col-lg-6" id="member_list_wrapper">
		<h1>Your Fellow DogEar Members</h1>
		<h4>See what books other members love and don't love.</h4>
	</div>
</div>
<div class="row">
	<div class="col-lg-offset-3 col-lg-6 index">
		<ul class="users">
			<% if @users %>
		  <% @users.order("last_name asc").each do |user| %>

		    <li>
		    	<h1><%= link_to "#{user.username}", user %></h1>
		    	<div class="row users_favs">
					<div class="col-lg-6">
		      	<p>Loved it!</p>
			      <% if user.favorite_books.empty? %>
			      	<span class="favorite_book">None Selected</span>
			      <% else %>
			      <div class="index_half">
			      	<%= image_tag user.favorite_books.first.image_url %><br>
			      	<span class="favorite_book">
			      		<%= user.favorite_books.first.title %> (<%= user.favorite_books.first.year %>)<br>
			      		<%= user.favorite_books.first.author %>
			      	</span>
			      </div>
			      		<div class="row">	
									<% if logged_in? %>
										<div class="col-sm-12 favs_not">
										<div id="book_message" class="smaller3 col-sm-6">
											<%= link_to "Add to My Favorites", share_path(user_id: @current_user.id, book_id: user.favorite_books.first.id), method: :post, remote: true, class: "favorite" %>
										</div>
										<div id="book_message" class="smaller3 col-sm-6">
											<%= link_to "I couldn't finish this", dislike_path(user_id: @current_user.id, book_id: user.favorite_books.first.id), method: :post, remote: true, class: "unfinished" %>
										</div>
										<hr class="red_line">
										</div>
									<% end %>
								</div>
			      <% end %>
			     </div>
		      <div class="col-lg-6">
		      <p>Not loved it!</p>
		      <% if user.hated_books.empty? %>
		      	<span class="favorite_book">None Selected</span>
		      <% else %>
		      	<div class="index_half">
			      	<%= image_tag user.hated_books.first.image_url %><br>
			      	<span class="favorite_book">
			      		<%= user.hated_books.first.title %> (<%= user.hated_books.first.year %>)<br>
			      		<%= user.hated_books.first.author %>
				      </span>
				    </div>	

		      	<div class="row">	
								<% if logged_in? %>
									<div class="col-sm-12 favs_not">
									<div id="book_message" class="smaller3 col-sm-6">
										<%= link_to "Add to My Favorites", share_path(user_id: @current_user.id, book_id: user.hated_books.first.id), method: :post, remote: true, class: "favorite" %>
									</div>
									<div id="book_message" class="smaller3 col-sm-6">
										<%= link_to "I couldn't finish this", dislike_path(user_id: @current_user.id, book_id: user.hated_books.first.id), method: :post, remote: true, class: "unfinished" %>
									</div>
									<hr class="red_line">
									</div>
								<% end %>
							</div>
							</div>
		      <% end %>
		    </li>
		  <hr class="red_line">
		  <% end %>
		</ul>
		<div class="paginate">
			<%= will_paginate %>
		</div>
		<% else %>
			<h1> There are no users yet </h1>
		<% end %>

	</div>
</div>
</div>
</div>

app/views/users/new.html.erb
<%= render 'layouts/header' %>

<div class="row sign_in_wrapper">
<div class="col-lg-8 col-md-offset-2">
    <div class="row" id="sign_in">
        <div class="col-lg-12" id="signin1">
          <h1>Create an Account</h1>
          <div id="account">
            <p>Can't wait to learn more about you!
            What books you like... what books you don't like</p>
          </div>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-12" id="signin2">
          
          <%= form_for(@user) do |f| %>
            <div class="row">
            <div class="col-lg-12">
                <%= render 'shared/error_messages' %>
            </div>
            </div>

            <div class="row">
            <div class="col-lg-6" id="essentials">
                <h3>The Essentials</h3>
                <%= f.label :username %>
                <%= f.text_field :username, class: 'form-control' %>

                <%= f.label :first_name %>
                <%= f.text_field :first_name, class: 'form-control' %>

                <%= f.label :last_name %>
                <%= f.text_field :last_name, class: 'form-control' %>

                <%= f.label :city %>
                <%= f.text_field :city, class: 'form-control' %>

                <%= f.label :state %><br>
                <%= f.select :state, options_for_select(us_states), class: 'form-control' %><br>

                <%= f.label :email %>
                <%= f.email_field :email, class: 'form-control' %>

                <%= f.label :password %>
                <%= f.password_field :password, class: 'form-control' %>

                <%= f.label :password_confirmation, "Confirmation" %>
                <%= f.password_field :password_confirmation, class: 'form-control' %>
            </div>
            <div class="col-lg-6 fun_stuff">
                <h3>The Fun Stuff</h3>
                <%= f.label :fav_author, "Favorite Author" %>
                <%= f.text_field :fav_author, class: 'form-control' %><br>
                <div class="field">
                 
                  <fieldset class="col-lg-offset-1 col-lg-11" id="group">
                    <legend>Pick your favorite Genres</legend>
                  <%= f.collection_check_boxes :genre_ids, Genre.all, :id, :name do |b| %>
                    <div class="collection-check-box">
                      <%= b.check_box %>
                      <%= b.label %>
                    </div>
                  <% end %>
                  </fieldset>
                </div>
            </div>
            </div>
            <hr class="thick_line">
            <div class="row">
            <div class="col-lg-offset-4 col-lg-4">
                <div id="signin_button">
                  <%= image_submit_tag("paw.png", class: "vel-button",
                    :onmouseover => "this.src='/assets/paw_hover.png'", 
                    :onmouseout => "this.src='/assets/paw.png'")  %>
                </div>
            </div>
            </div>
          <% end %>
          
        </div>
    </div>
</div>

app/views/users/show.html.erb
<%= render 'layouts/header' %>

<div class="row">
<div class="col-lg-offset-3 col-lg-6"> 
	<div id="profile_info">
		
		<h1><%= @user.username %></h1>
		<div class="row">
		<div class="col-lg-offset-3 col-lg-6" id="edit_row">
			<% if current_user.id == @user.id %>
				<h2><%= @user.first_name %> <%= @user.last_name %></h2>
			<% end %>
			<table>
				<tr>
					<td class="row_name">Location: </td> 
					<td class="row_selection"><%= @user.city %>, <%= @user.state %></td>
				<tr>
					<td class="row_name">Favorite Author: </td>
					<td class="row_selection"><%= @user.fav_author %></td>
				</tr>
				<tr>
					<td class="row_name">Favorite Genres: </td>
			<% if @user.genres.any? %>
				<td class="row_selection"><ul> 
					<% @user.genres.each do |genre| %>
						<li>
							<%= genre.name %>
						</li>
					<% end %>
				</ul></td>
			<% end %>
		</table>
			<% if current_user.id == @user.id %>
				<div id="edit_img">
					<%= link_to image_tag("edit_hover.png", 
						:onmouseover => "this.src='/assets/edit.png'", 
						:onmouseout => "this.src='/assets/edit_hover.png'"), 
						edit_user_path, class: "vel-button" %>
					<br><br>
				</div>	
			<% end %>	
		</div>		
		</div>
	</div>
</div>
</div>


<div class="row">
<div class="col-lg-offset-2 col-lg-8">
	<div class="row">
	<div class="col-lg-6 profile_books">
		<% if @user.favorites.any? %>
			<h2>Books I Love<br> (<%= @user.favorite_books.count %>)
			</h2>
			<ol class="big_number sortable">
				<% @user.favorite_books.each do |favorite| %>
					<% Book.where(id: favorite.id).each do |book| %>
						<li class="sorted">
							<div id="rankings">
								<%= image_tag book.image_url %>
								<br><br>
								<%= book.title %><br>
								(<%= book.year %>)
								<br><span class="smaller"><%= book.author %></span>
								<span class="smaller"><br>
									<% if current_user.id == @user.id %>
										<%= link_to "Remove from list", remove_path(user_id: @current_user.id, book_id: book.id), method: :post %></span>
									<% end %>
							</div>
							<hr class="red_line">
						</li>
					<% end %>
				<% end %>
			</ol>
		<% end %>
	</div>
	<div class="col-lg-6 profile_books">	
		<% if @user.hated_books.any? %>
			<h2>Books I Don't<br> (<%= @user.hated_books.count %>)</h2>
			<ol class="big_number sortable">
				<% @user.hated_books.each do |unfinished| %>
					<% Book.where(id: unfinished.id).each do |book| %>
						<li class="sorted">
							<div id="rankings">
								<%= image_tag book.image_url %>
								<br><br>
								<%= book.title %><br>
								(<%= book.year %>) 
								<br><span class="smaller"><%= book.author %></span><br>
								<span class="smaller">
									<% if current_user.id == @user.id %>
										<%= link_to "Remove from list", remove_path(user_id: @current_user.id, book_id: book.id), method: :post %></span>
									<% end %>
							</div>
							<hr class="red_line">
						</li>
					<% end %>
				<% end %>
			</ol>
		<% end %>
	</div>
	</div>
</div>
</div>