config/routes.rb
Rails.application.routes.draw do

  get 'users/new'

  get 'static/home'

  get 'bookstores/new'

  post 'bookstores/create'

  get 'books/index'

  get 'books/new'

  get 'books/show'

  post 'books/store'

  get 'bookstores/coord' => 'bookstores#find_coordinates', as: :coordinates
  get 'bookstores/map' => 'bookstores#map', as: :map

  get 'users/index'

  get 'users/show'

  post '/submit_map'  => 'bookstores#map'
  get 'signup' => 'users#new'
  get   'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  get 'logout'  => 'sessions#destroy'
  
  post '/share' => 'books#share'
  post '/dislike' => 'books#dislike'
  post '/remove' => 'books#remove'

  # root 'welcome#index'

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
    resources :users
    resources :books
    resources :bookstores

  root 'static#home'

  
end

app/models/book.rb
class Book < ActiveRecord::Base

	has_many :readers, through: :favorites, source: :user
	has_many :favorites

	has_many :haters, through: :unfinisheds, source: :user
	has_many :unfinisheds
	
	validates_uniqueness_of :gr_id

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  include SessionsHelper

  def new
    @bookstore = Bookstore.new
  end

  def index
    current_user
    client = Goodreads.new
    @client = client

    @book = params[:choice_title]
    @books = client.search_books(@book)
    @book_list = []

    @books.results.work.each {|book|
      if Book.find_by(gr_id: book.best_book.id)
        b = Book.find_by(gr_id: book.best_book.id)
      else
        b = Book.create({
        title: book.best_book.title,
        author: book.best_book.author.name, 
        year: book.original_publication_year, 
        image_url: book.best_book.image_url,
        gr_id: book.best_book.id
        })
      end
    @book_list << b
  }
  end

  def remove
    user = User.find(params[:user_id])
    removed = Book.find(params[:book_id])
    puts "PULLING UP REMOVED:"
    puts removed.id
    book = user.favorites.find_by(book_id: removed.id)
    puts "++++++++++++++++++++++++++++"
    puts book
    book.destroy
    flash[:success] = "Item has been removed"
    redirect_to :back
  end

  def share
    puts "SHARING BOOK"

    user = User.find(params[:user_id])
    book = Book.find(params[:book_id])

    unless user.hated_books.include?(book)
      puts "ADDING BOOK"
      user.favorite_books << book
      flash[:success] = "Your book was added"
      redirect_to :back
    else
      flash[:success] = "You have already stated that you could not finish this book."
      @switch = false
      redirect_to :back
    end
  end

  def dislike
    puts "DISLIKING BOOK"

    user = User.find(params[:user_id])
    book = Book.find(params[:book_id])

    unless user.favorite_books.include?(book)
      puts "HATING BOOK"
      user.hated_books << book
      flash[:success] = "Your book was added"
      redirect_to :back
    else
      flash[:danger] = "You have already listed this book as a favorite."
      @switch = false
      redirect_to :back
    end
  end

  def store
    @bookstore = Bookstore.create(bookstore_params)
    redirect_to root_path
  end

  def show
  end

  

end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/index.html.erb
<%= render 'layouts/header' %>

<div class="row">
	<div class="col-md-offset-4 col-md-4" id="book_lookup">
		<% if @book %>
			<h3>Search Matches for:</h3>
			<span class="searched"><%= @book.upcase %></span>
		<% else %>
			<h1>Search for a book</h1>
		<% end %>
	</div>
</div>

<div class="row">
<div class="col-md-offset-3 col-md-6">

	<div class="list">
		<% if !@books.empty? %>
			<ol class="big_number">
			<% @book_list.each do |book| %>
				<li>
					<div id="rankings">
						<%= image_tag book.image_url %>
						<br><br>
						<%= book.title %>
						(<%= book.year %>)<br>
						<span class="smaller"><%= book.author %></span>
						<%= book.id %>,<%= book.gr_id %>
					</div>
			
					<div class="row">	
							<% if logged_in? %>
								<div class="col-sm-12 favs_not">
								<div id="book_message" class="smaller3 col-sm-6">
									<%= link_to "Add to My Favorites", share_path(user_id: @current_user.id, book_id: book.id), method: :post, remote: true, class: "favorite" %>
								</div>
								<div id="book_message" class="smaller3 col-sm-6">
									<%= link_to "I couldn't finish this", dislike_path(user_id: @current_user.id, book_id: book.id), method: :post, remote: true, class: "unfinished" %>
								</div>
								<hr class="red_line">
								</div>
							<% end %>
						</div>
						<hr class="red_line">
				</li>
			<% end %>
			</ol>
				<hr>
		<% else %>
			<ul>
				<li>Sorry, no listings found for your selection.</li>
			</ul>
		<% end %>
	</div>

</div>
</div>

app/views/books/new.html.erb
	<%= render 'layouts/header' %>

<br>
<div>
<div class="row">
	<div class="col-lg-offset-2 col-lg-8" id="book_search_head">
	<div class="col-lg-7" id="book_lookup">
		<h1>Search by title or author:</h1>
	</div>
	<div class="col-lg-3">
		<%= form_tag(books_index_path, :method=>"get") do %>
	      <%= text_field_tag(:choice_title) %><br>
	      <div id="search_button">
          <%= image_submit_tag("paw.png", 
            :onmouseover => "this.src='/assets/paw_hover.png'", 
            :onmouseout => "this.src='/assets/paw.png'", class: "vel-button") %>
        </div>
	  <% end %>
	</div>
	</div>
	</div>
</div>

<div class="row">
	<div class="col-md-offset-2 col-md-8">

		<div class="col-lg-6 dogear_lists" id="divider">
			<h2>Most Popular on DogEar</h2>
			<ol class="big_number">
			<% Book.all.order("favorites_count desc").take(10).each do |book| %>
				<li>
					<div id="rankings">
						<%= image_tag book.image_url %>
						<br><br>
						<%= book.favorites_count %> <span class="smaller2">times on Favorites Lists</span><br>
						<%= book.title %><br>
						(<%= book.year %>)
						<br><span class="smaller"><%= book.author %></span>
					</div>
					
					<div class="row">	
							<% if logged_in? %>
								<div class="col-sm-12 favs_not">
								<div id="book_message" class="smaller3 col-sm-6">
									<%= link_to "Add to My Favorites", share_path(user_id: @current_user.id, book_id: book.id), method: :post,  class: "favorite" %>
								</div>
								<div id="book_message" class="smaller3 col-sm-6">
									<%= link_to "I couldn't finish this", dislike_path(user_id: @current_user.id, book_id: book.id), method: :post,  class: "unfinished" %>
								</div>
								<hr class="red_line">
								</div>
							<% end %>
						</div>
						<hr class="red_line">
					</li>
			<% end %>
			</ol>
		</div>

		<div class="col-lg-6 dogear_lists">
			<h2>Least Popular on DogEar</h2>
			<ol class="big_number">
			<% Book.all.order("unfinisheds_count desc").take(10).each do |book| %>
					<li>
						<div id="rankings">
							<%= image_tag book.image_url %>
							<br><br>
							<%= book.unfinisheds_count %> <span class="smaller2">times on Unfinished Lists</span><br>
							<%= book.title %><br>
							(<%= book.year %>)
							<br><span class="smaller"><%= book.author %></span>
						</div>

						<div class="row">	
							<% if logged_in? %>
								<div class="col-sm-12 favs_not">
								<div id="book_message" class="smaller3 col-sm-6">
									<%= link_to "Add to My Favorites", share_path(user_id: @current_user.id, book_id: book.id), method: :post, class: "favorite" %>
								</div>
								<div id="book_message" class="smaller3 col-sm-6">
									<%= link_to "I couldn't finish this", dislike_path(user_id: @current_user.id, book_id: book.id), method: :post,  class: "unfinished" %>
								</div>
								<hr class="red_line">
								</div>
							<% end %>
						</div>
						<hr class="red_line">
					</li>
			<% end %>
			</ol>
		</div>

	</div>
</div>
</div>

 <script type="text/javascript">
// $(document).ready(function() {
// 	// alert("Hi");

// 	$('.favorite').click(function() {
// 		$(this).parent().text("Added to Favorites");
// 	})

// 	$('.unfinished').click(function() {
// 		$(this).parent().text("Sorry, you didn't like this.");
// 	})

// });
// </script>
	

  

app/views/books/share.js.erb
$(document).ready(function() {
	// alert("Hi");
	// $('#book_message').text("WOOF!... woof.");
});

app/views/books/show.html.erb
<%= render 'layouts/header' %>

<h1>Search Matches for <%= @book %></h1>