config/routes.rb
Rails.application.routes.draw do

  get 'users/new'

  get 'static/home'

  get 'bookstores/new'

  post 'bookstores/create'

  get 'books/index'

  get 'books/new'

  get 'books/show'

  post 'books/store'

  get 'bookstores/coord' => 'bookstores#find_coordinates', as: :coordinates
  get 'bookstores/map' => 'bookstores#map', as: :map

  get 'users/index'

  get 'users/show'

  post '/submit_map'  => 'bookstores#map'
  get 'signup' => 'users#new'
  get   'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  get 'logout'  => 'sessions#destroy'
  
  post '/share' => 'books#share'
  post '/dislike' => 'books#dislike'
  post '/remove' => 'books#remove'

  # root 'welcome#index'

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
    resources :users
    resources :books
    resources :bookstores

  root 'static#home'

  
end

app/views/layouts/_footer.html.erb
<!-- 
<footer class="row navbar">
	<p>
		<span class="align_left">&#169;2015, DogEar</span>
		<span class="align_right">designed by Vivek Gahunia</span>
	</p>
</footer> -->

app/views/layouts/_header.html.erb
<div class="row">
<div class="col-lg-12" id="login_username">
	<% if logged_in? %>
		<p>
			<span id="header_hi">Welcome, <%= @current_user.first_name %></span>
			<span id="logout"><%= link_to "Sign Out", logout_path %></span>
		</p>
	<% end %>
</div>
</div>


<div class="row">
<div class="col-lg-12" id="logo">
	<div><%= link_to image_tag("logo_3.png", 
		:onmouseover => "this.src='/assets/logo_hover.png'", 
		:onmouseout => "this.src='/assets/logo_3.png'"), 
		root_path, class: "vel-button1" %>
	</div>
	<nav id="header_menu" class="row">
		<ul>
			<li><%= link_to "Search Books", books_new_path, class: "vel-button" %></li>
			<li><%= link_to "Search Bookstores", '#', id: "stores", class: "vel-button" %></li>
			<% if logged_in? %>
				<li><%= link_to "My Profile", current_user, class: "vel-button" %></li>
				<li><%= link_to "Member List", users_path, class: "vel-button" %></li>
			<% else %>
				<li><%= link_to "Sign in", login_path, class: "vel-button" %></li>
				<li><%= link_to "Sign Up", signup_path, class: "vel-button" %></li>
			<% end %>
		</ul>
	</nav>
</div>
</div>

app/views/layouts/_header_min.html.erb
<div class="row">
<div class="col-lg-12" id="logo">
	<div><%= link_to image_tag("logo_3.png", 
		:onmouseover => "this.src='assets/logo_hover.png'", 
		:onmouseout => "this.src='/assets/logo_3.png'"), 
		root_path, class: "vel-button1" %>
	</div>
	<nav id="header_menu" class="row">
		<ul>
			<li><%= link_to "Sign in", login_path, class: "vel-button" %></li>
			<li><%= link_to "Sign Up", signup_path, class: "vel-button" %></li>
		</ul>
	</nav>
</div>
	
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Dogear</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <link href='https://fonts.googleapis.com/css?family=Glegoo' rel='stylesheet' type='text/css'><link href='https://fonts.googleapis.com/css?family=Petit+Formal+Script' rel='stylesheet' type='text/css'>
  <script src="//maps.google.com/maps/api/js?v=3.13&amp;sensor=false&amp;libraries=geometry" type="text/javascript"></script>
	<script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js' type='text/javascript'></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/underscore.js/1.8.3/underscore-min.js"></script>
  <script src="https:////cdn.jsdelivr.net/velocity/1.2.3/velocity.min.js"></script>
  <script src="https://cdn.jsdelivr.net/velocity/1.2.3/velocity.ui.min.js"></script>
  <%= csrf_meta_tags %>
</head>

<body class="container-fluid" id="body_full">
	<% flash.each do |message_type, message| %>
    <div class="alert alert-<%= message_type %>" id="flash_alert"><%= message %></div>
  <% end %>
	
<div id="content">
<%= yield %>

</div>
<%= render 'layouts/footer' %>

</body>
</html>